getwd()
setwd("D:/ibs/business intelligence & analytics")
framingham=read.csv("D:/ibs/business intelligence & analytics/framingham.csv")
str(framingham)
summary(framingham)
library(caTools)
set.seed(1000)
split=sample.split(framingham$TenYearCHD,SplitRatio = 0.65)
split
summary(split)
train=subset(framingham,split==TRUE)
str(train)
test=subset(framingham,split==FALSE)
str(test)
framinghamLog=glm(TenYearCHD~.,family=binomial,data = train)
summary(framinghamLog)
predictionTest=predict(framinghamLog,type="response",newdata=test)
table(test$TenYearCHD,predictionTest>0.5)
