setwd("D:/ibs/business intelligence & analytics") #This sets the working directory to "D:/ibs/business intelligence & analytics", which is where your data file is located.
fv=read.csv("Placement_Data.csv")

placement<-read.csv("Placement_Data.csv")
str(placement)
head(placement)

placement<-placement[-1]
placement<-placement[-14]
str(placement)

data=subset(placement,select = -sl_no) #alternate method
data=subset(placement,select = -salary) #alternate method

placement$status<-as.factor(placement$status) #This converts the status column in the placement data frame to a factor, which is a categorical variable in R.
install.packages("caret")
library(caret)

set.seed(1234)
index<-createDataPartition(placement$status,p=0.8,list=F) #This creates a partition of the data, splitting it into training and testing sets. 80% of the data is used for training, and 20% for testing. index is a vector of row indices for the training set.
dataTrain<-placement[index,] #This creates the training set using the indices generated by createDataPartition()
dataTest<-placement[-index,] #This creates the testing set using the rows not included in the training set indices.
dim(dataTrain) #This displays the dimensions (number of rows and columns) of the training set.
dim(dataTest)

fit<-train(status~.,data=dataTrain,method="knn",trControl=trainControl(method="cv",number=10))
#This trains a k-nearest neighbors (k-NN) model using the training set. 
#The status ~ . formula specifies that status is the response variable, 
#and all other columns are predictors. The method="knn" argument specifies 
#that the k-NN algorithm should be used. The trControl=trainControl(method="cv", number=10) 

#argument specifies that 10-fold cross-validation should be used to evaluate the model's performance.
predictions<-predict(fit,newdata = dataTest) #This line uses the trained k-NN model (fit) to make predictions on the test dataset (dataTest). The predict function generates predicted values for the status column based on the model and the test data. The predicted values are stored in the predictions vector.
confusionMatrix(predictions,dataTest$status) #This line creates a confusion matrix to evaluate the performance of the model. The confusionMatrix function compares the predicted values (predictions) with the actual values (dataTest$status). It returns a confusion matrix, which includes metrics such as accuracy, sensitivity, specificity, and more, to assess how well the model performed.

boxplot(placement$ssc_p ~ placement$status)
(table(placement$status,placement$degree_t))
barplot((table(placement$status,placement$degree_t)))

#naive bayes
library(e1071)
set.seed(7)
trainControl<-trainControl(method="repeatedcv", number=10, repeats=3)
nb_model <- naiveBayes(status ~ ., data = dataTrain, trControl=trainControl)
nb_predictions <- predict(nb_model, dataTest)
confusionMatrix(nb_predictions, dataTest$status)

#decision trees
set.seed(7)
fit.cart<-train(status~.,data=dataTrain,method="rpart",trControl=trainControl)
rpart <- predict(fit.cart, dataTest)
confusionMatrix(rpart, dataTest$status)
