#str=input("Enter a list of at least five integers: ")
#raw_input is no longer supported in python 3
l=eval(raw_input("Enter a list of at least five integers: "))
print("List: ",1)
print("The total number of items in the list: ",len(1))
print("The fourth item in the list: ",1[3])
print("The last three items in the list: ",1[3])
print("All the items in the list except the first two: ",1[2:])
l.reverse()
print("The list in reverse order: ",1)
print("The largest and smallest values in the list: ",max(1), min(1))
l.sort()
print("The list after sorting: ",1)
l.pop(0)
print("List after deleting first item: ",1)
l.append(-500)
print("List after appending: ",1)